DROP USER "TAXI" CASCADE;

CREATE USER "TAXI";

ALTER USER "TAXI"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

GRANT CREATE SESSION, RESOURCE TO TAXI;
ALTER USER TAXI QUOTA 100M ON users;

GRANT "CONNECT" TO "TAXI" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "TAXI" WITH ADMIN OPTION;
GRANT "DBA" TO "TAXI" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "CAPTURE_ADMIN" TO "TAXI" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "TAXI" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "TAXI" WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "TAXI" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "TAXI" WITH ADMIN OPTION;
GRANT "CTXAPP" TO "TAXI" WITH ADMIN OPTION;
GRANT "EM_EXPRESS_ALL" TO "TAXI" WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO "TAXI" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO "TAXI" WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO "TAXI" WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "TAXI" WITH ADMIN OPTION;
GRANT "SODA_APP" TO "TAXI" WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO "TAXI" WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO "TAXI" WITH ADMIN OPTION;
GRANT "EM_EXPRESS_BASIC" TO "TAXI" WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO "TAXI" WITH ADMIN OPTION;
GRANT "XDBADMIN" TO "TAXI" WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO "TAXI" WITH ADMIN OPTION;




